### ISSUE TITLE
format为Pasword时报错

### ISSUE THREAD

**Issue by imvicchen** [cddsgtc/cddv#1]
Uncaught TypeError: a.test is not a function
事例密码的 都报此错误～

**Comment by cddsgtc** [comment]
@imvicchen 
打算近期重新写下这个插件，提供更方便的功能和自定义组合。目前的插件跟elementui之类的第三方多重组件结合还是有点问题的。

你的错误可能是理解错了。

**Comment by cddsgtc** [comment]
resolve
