### ISSUE TITLE
ES5版本是需要require库吗

### ISSUE THREAD

**Issue by think2cat** [cddsgtc/cddv#2]

**Comment by cddsgtc** [comment]
@think2cat 
require库只是开发时需要的，这个不需要，这个目前还没做umd适配，今天我给出一个吧。

**Comment by cddsgtc** [comment]
@think2cat 
已添加`vue`浏览器直用自动安装版本。
`es5`版本只不过为了方便感兴趣的人查看源码，现在源码已经改为`src/cddv.js`文件中了。

**Comment by cddsgtc** [comment]
解决
